version: '3.8'
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mssql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "passwordSEMENTARA!"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql-data:/var/opt/mssql
      